import Head from "next/head";
import { AiFillLinkedin, AiFillInstagram, AiFillGithub, AiFillHtml5 } from "react-icons/ai";
import { DiCss3 } from "react-icons/di";
import { IoLogoJavascript, IoLogoNodejs } from "react-icons/io"
import { SiMysql, SiMongodb, SiGraphql, SiFlutter } from "react-icons/si"
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/peeps-avatar-alpha.png";
// import CardItem from "./items/card";
import Image from "next/image";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>pilotkode</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen mb-5">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">PILOTKODE</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://linktr.ee/rendyekafebriyanto" target="_blank" rel="noreferrer"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Rendy Eka F
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Developer and QA Engineer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Mahasiswa IT yang suka belajar web development dan automation
              testing
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a
                href="https://www.instagram.com/pilotkode/?igshid=ZDdkNTZiNTM="
                target="_blank" rel="noreferrer"
              >
                <AiFillInstagram />
              </a>

              <a
                href="https://www.linkedin.com/in/rendyekafebriyanto/"
                target="_blank" rel="noreferrer"
              >
                <AiFillLinkedin />
              </a>
              <a
                href="https://github.com/RendTI3080"
                target="_blank" rel="noreferrer"
              >
                <AiFillGithub />
              </a>
            </div>
          </div>
          <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-5">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Tentang Saya</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Tertarik pada it sejak awal tahun 2021 mendorong diri saya untuk
              terus berkembang dan mempelajari banyak hal mengenai web
              development. Mempelajari front end dan backend selama kurung waktu
              2 tahun ini membuat saya senang akan perkembangan diri saya dari
              waktu ke waktu.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Selain aktif berorganisasi selama kuliah saya juga aktif mengajar
              bidang programming untuk anak-anak umur 6-15 tahun. Mengajarkan
              mobile design, basic programming with scratch, dan web development
              selama kurang 1 tahun belakangan ini. sudah lebih dari 200 siswa
              dan 3 event perlombangan coding untuk anak-anak sudah sukses saya
              laksanakan. 95% siswa lulus dengan nilai diatas 85.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Selain kuliah dan mengajar saya juga aktif dalam mengembangkan
              platform podcast yang saya beri nama pilot kode, dimana di dalam
              podcast saya. saya banyak membahas tips and trick mahasiswa it dan
              juga perkembangan teknologi yang sedan naik daun belakangan ini.
              Saya berharap podcast saya bisa menjadi wadah informasi dan juga
              kedepannya saya ingin mengembakan podcast saya untuk bisa menjadi
              jembatan antara ahli digital yang sudah terjuan di dunia industri
              dengan mahasiswa it yang nanti akan menjadi penerus dari digital
              talent di Indonesia ini.
            </p>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Teknologi</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Selama kurang lebih satu tahun setengah terakhir ini. banyak tools
              yang saya pelajari. Mulai dari sisi backend seperti javscript node
              js, mysql, mongodb, graphql hingga teknologi front end seperti
              html, css, tailwind, dan react js.
              Selain mempelajari dari sisi development saya juga tidak lupa
              mempelajari sisi testing karena sempat mendapatkan mata kuliah
              software testing saya mempelajari basic testing, cypress, mocha,
              chai, dan juga katalon untuk mendukung dalam membuat testing pada
              aplikasi yang saya buat
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Setelah web development saya juga mulai tertarik pada bidang mobile
              development. Dimulai dari teman yang mengajak membuat proyek dimana
              saya membuat logic dan endpoint dengan node js. Pengambangan mobile
              dengan flutter saat ini sedang naik daun. dikarenakan kemudahan dan tidak
              perlu memakai laptop super kencang untuk mendevelop mobile app dengan flutter
            </p>
          </div>
          <div className="my-10">
            <div className="text-5xl flex flex-wrap justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillHtml5/>
              <DiCss3/>
              <IoLogoJavascript/>
              <IoLogoNodejs/>
              <SiMysql/>
              <SiMongodb/>
              <SiGraphql/>
              <SiFlutter/>
            </div>
          </div>
          <div className="my-20">
            {/* <CardItem/> */}
          </div>
        </section>
      </main>
    </div>
  );
}
